import Head from 'next/head';
import Image from 'next/image';
import BuyCoffee from '../components/BuyCoffee';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Buy me a coffee!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <BuyCoffee />
    </>
  );
}
